version: '3.8'
services:
  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  park_app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - ./:/app  # Mount the application code into the container  -
    env_file:
          - .env
volumes:
  mongodb_data:
